// this would normally be in separate files but because it was auto generated, I chose to keep it in a single file.
using Newtonsoft.Json;
#pragma warning disable CS8618

namespace BossTweet.Core.Entities.Twitter;

public class Tweet
{
    [JsonProperty("data")]
    public Data Data { get; set; }
}

#region autogenerated

public class Attachments
{
}

public class Description
{
    [JsonProperty("urls")]
    public List<Url> Urls { get; set; }
}

public class Annotation
{
    [JsonProperty("start")]
    public int Start { get; set; }

    [JsonProperty("end")]
    public int End { get; set; }

    [JsonProperty("probability")]
    public double Probability { get; set; }

    [JsonProperty("type")]
    public string Type { get; set; }

    [JsonProperty("normalized_text")]
    public string NormalizedText { get; set; }
}

public class Data
{
    [JsonProperty("author_id")]
    public string AuthorId { get; set; }

    [JsonProperty("entities")]
    public Entities Entities { get; set; }

    [JsonProperty("id")]
    public string Id { get; set; }

    [JsonProperty("text")]
    public string Text { get; set; }

    [JsonProperty("attachments")]
    public Attachments Attachments { get; set; }

    [JsonProperty("conversation_id")]
    public string ConversationId { get; set; }

    [JsonProperty("created_at")]
    public DateTime CreatedAt { get; set; }

    [JsonProperty("geo")]
    public Geo Geo { get; set; }

    [JsonProperty("lang")]
    public string Lang { get; set; }

    [JsonProperty("possibly_sensitive")]
    public bool PossiblySensitive { get; set; }

    [JsonProperty("public_metrics")]
    public PublicMetrics PublicMetrics { get; set; }

    [JsonProperty("reply_settings")]
    public string ReplySettings { get; set; }

    [JsonProperty("source")]
    public string Source { get; set; }

}

public class Entities
{
    [JsonProperty("mentions")]
    public List<Mention> Mentions { get; set; }

    [JsonProperty("hashtags")]
    public List<Hashtag> Hashtags { get; set; }

    [JsonProperty("urls")]
    public List<Url> Urls { get; set; }

    [JsonProperty("annotations")]
    public List<Annotation> Annotations { get; set; }

    [JsonProperty("url")]
    public Url Url { get; set; }

    [JsonProperty("description")]
    public Description Description { get; set; }
}

public class Hashtag
{
    [JsonProperty("start")]
    public int Start { get; set; }

    [JsonProperty("end")]
    public int End { get; set; }

    [JsonProperty("tag")]
    public string Tag { get; set; }
}

public class Image
{
    [JsonProperty("url")]
    public string Url { get; set; }

    [JsonProperty("width")]
    public int Width { get; set; }

    [JsonProperty("height")]
    public int Height { get; set; }
}

public class Mention
{
    [JsonProperty("start")]
    public int Start { get; set; }

    [JsonProperty("end")]
    public int End { get; set; }

    [JsonProperty("username")]
    public string Username { get; set; }

    [JsonProperty("id")]
    public string Id { get; set; }
}

public class Url
{
    [JsonProperty("start")]
    public int Start { get; set; }

    [JsonProperty("end")]
    public int End { get; set; }

    [JsonProperty("url")]
    public string UrlString { get; set; }

    [JsonProperty("expanded_url")]
    public string ExpandedUrl { get; set; }

    [JsonProperty("display_url")]
    public string DisplayUrl { get; set; }

    [JsonProperty("media_key")]
    public string MediaKey { get; set; }

    [JsonProperty("status")]
    public int? Status { get; set; }

    [JsonProperty("title")]
    public string Title { get; set; }

    [JsonProperty("description")]
    public string Description { get; set; }

    [JsonProperty("unwound_url")]
    public string UnwoundUrl { get; set; }

    [JsonProperty("images")]
    public List<Image> Images { get; set; }

    [JsonProperty("urls")]
    public List<Url> Urls { get; set; }

}

public class Geo
{
}

public class Includes
{
    [JsonProperty("users")]
    public List<User> Users { get; set; }
}

public class PublicMetrics
{
    [JsonProperty("retweet_count")]
    public int RetweetCount { get; set; }

    [JsonProperty("reply_count")]
    public int ReplyCount { get; set; }

    [JsonProperty("like_count")]
    public int LikeCount { get; set; }

    [JsonProperty("quote_count")]
    public int QuoteCount { get; set; }

    [JsonProperty("followers_count")]
    public int FollowersCount { get; set; }

    [JsonProperty("following_count")]
    public int FollowingCount { get; set; }

    [JsonProperty("tweet_count")]
    public int TweetCount { get; set; }

    [JsonProperty("listed_count")]
    public int ListedCount { get; set; }
}

public class User
{
    [JsonProperty("created_at")]
    public DateTime CreatedAt { get; set; }

    [JsonProperty("description")]
    public string Description { get; set; }

    [JsonProperty("entities")]
    public Entities Entities { get; set; }

    [JsonProperty("id")]
    public string Id { get; set; }

    [JsonProperty("location")]
    public string Location { get; set; }

    [JsonProperty("name")]
    public string Name { get; set; }

    [JsonProperty("pinned_tweet_id")]
    public string PinnedTweetId { get; set; }

    [JsonProperty("profile_image_url")]
    public string ProfileImageUrl { get; set; }

    [JsonProperty("protected")]
    public bool Protected { get; set; }

    [JsonProperty("public_metrics")]
    public PublicMetrics PublicMetrics { get; set; }

    [JsonProperty("url")]
    public string Url { get; set; }

    [JsonProperty("username")]
    public string Username { get; set; }

    [JsonProperty("verified")]
    public bool Verified { get; set; }
}

#endregion
